### ISSUE TITLE
Literal Boolean values in YAML

### ISSUE THREAD

**Issue by bbaassssiiee** [thegeeklab/ansible-later#224]
There is a rule that states that literal Boolean values should start with a capital letter, i.e. literal bools should be written as `True/False` or `yes/no`:

https://github.com/thegeeklab/ansible-later/blob/0b625d3bb3508666c6b9077e516bd6ea6389e5ad/ansiblelater/rules/CheckLiteralBoolFormat.py#L9

This rule has a couple of problems:

- It is incompatible with the default settings of [yamllint](https://github.com/adrienverge/yamllint), yamllint is called by ansible-lint and molecule.
- It does not enforce a standard code-style where you simply stick to `true` and `false` because `yes` and `no` are also accepted.
- It is incompatible with JSON, return values of Ansible modules are encoded as JSON.
- The values are actually represented by Ansible in lowercase:

```yaml
#!/usr/bin/env ansible-playbook
---

- name: true or false?
  hosts: all
  gather_facts: false

  tasks:

    - name: "all these boolean inputs evaluate to 'true'"
      debug:
        msg: "{{ item | bool}}"
      with_items:
        - true
        - True
        - TRUE
        - yes
        - Yes
        - YES
        - on
        - On
        - ON

    - name: "all these boolean inputs evaluate to 'false'"
      debug:
        msg: "{{ item | bool}}"
      with_items:
        - false
        - False
        - FALSE
        - no
        - No
        - NO
        - off
        - Off
        - OFF
```
