### ISSUE TITLE
Namespace violation

### ISSUE THREAD

**Issue by bbaassssiiee** [thegeeklab/ansible-later#227]
https://github.com/thegeeklab/ansible-later/blob/427356cf617f097fce66dd32b2a227a6d6bbf59c/ansiblelater/rules/CheckDeprecated.py#L22

The tag `skip_ansible_lint` is valid when using `ansible-lint`, this rule tries to deprecate the tag of another tool.

```yaml
- name: Create python3 virtualenv
  pip:
    name:
      - pip
      - wheel
      - setuptools
    state: latest
    virtualenv: "{{ mezzanine_venv_path }}"
    virtualenv_command: /usr/bin/python3 -m venv
  tags:
    - skip_ansible_lint
```

ERROR shown by ansible-later:
```
ERROR: [ANSIBLE9999] Standard 'Deprecated features should not be used' not met:
... roles/mezzanine/tasks/django.yml:19: 'skip_ansible_lint' is deprecated and should not be used anymore. Use 'skip_ansible_later' instead.
```

After updating the tag to `skip_ansible_later` ansible-lint shows this error:
```WARNING  Listing 1 violation(s) that are fatal
[403] Package installs should not use latest
roles/mezzanine/tasks/django.yml:19
Task/Handler: Create python3 virtualenv
```

I'd rather use ansible-lint and ansible-later because they can complement each other.

I suggest that if both tags are present the check passes.
