### ISSUE TITLE
Blocks and ANSIBLE0001 (empty line between tasks)

### ISSUE THREAD

**Issue by robertdebock** [thegeeklab/ansible-later#239]
This code:

```yaml
- name: some block
  block:
    - name: first task
      setup:
  rescue:
    - name: rescue task
      setup::
```

triggers this warning: `ERROR: [ANSIBLE0001] Standard 'Single tasks should be separated by empty line' not met:`.

To fix the warning, this structure should be used:

```yaml
- name: some block
  block:
    - name: first task
      setup:
  rescue:

    - name: rescue task
      setup::
```

(A newline was added between `rescue:` and `-name: rescue task`.)

In my opinion the fixed code (below snippet) is not very logical. I think this is an unexpected advice. Please let me know your thoughts.
