### ISSUE TITLE
Empty line after `handlers:` required.

### ISSUE THREAD

**Issue by robertdebock** [thegeeklab/ansible-later#248]
An empty line after specifying `handlers:` is required to pass ansible-later.

This example:

```yaml
  tasks:
    - name: do something

  handlers:

    - name: do something else
```

Would return this error: `ERROR: [ANSIBLE0001] Standard 'Single tasks should be separated by empty line' not met.`

Just like `tasks:`, I think an empty line is not required, my ideal format would be:

```yaml
  tasks:
    - name: do something

  handlers:
    - name: do something else
```
