### ISSUE TITLE
Ansible later fails with traceback for command module with only argv

### ISSUE THREAD

**Issue by stanislaw55** [thegeeklab/ansible-later#47]
If you put following task in role/playbook, `ansible-later` will fail with traceback. Problem is with line 128 in file `ansiblelater/rules/ansiblefiles.py` which assumes that on of two scenarios happen:
 - either command uses free form i.e.
```yaml
- name: Task that is parsed just fine
  command: echo something
```
 - or using `cmd` parameter
```yaml
- name: Task that is parsed just fine
  command: 
    cmd: echo something
```

but there's also one more Ansible-valid usage of command which is

```yaml
- name: Task that causes traceback
  command:
    argv:
      - echo
      - something
```

and that causes traceback.

I'll try to come up with a patch
