### ISSUE TITLE
More intelligent check for module instead of command usage

### ISSUE THREAD

**Issue by tboerger** [thegeeklab/ansible-later#582]
For some role I'm using `shell` instead of `get_url` because the output gets directly piped into another command. In that case I'm getting an error:

```
WARNING: [ANSIBLE0008] Standard 'Commands should not be used in place of modules' not met:
... tasks/main.yml:3: curl command used in place of get_url or uri module
```

To give a real example, that's what I'm doing:

```
- name: Download repo key
  shell:
    cmd: curl -sSL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x52B59B1571A79DBC054901C0F6BC817356A3D45E" | gpg --dearmor --output /usr/share/keyrings/golang-archive-keyring.gpg
    creates: /usr/share/keyrings/golang-archive-keyring.gpg
```

It would be great if ansible-later could detect correctly that `get_url` won't work as the curl output directly gets piped into gpg. I guess same applies for various cases where curl is used in combination with pipes.
